Make scripts more user friendly
Add mac support to MicroSoftFontInstaller

diff --git a/scripts/MicrosoftFontInstaller b/scripts/MicrosoftFontInstaller
--- a/scripts/MicrosoftFontInstaller
+++ b/scripts/MicrosoftFontInstaller
@@ -3,51 +3,83 @@
 # MicrosoftFontInstaller.zsh
 # The MIT License (MIT) [https://opensource.org/licenses/MIT]
 # Copyright (c) 2016 Gregory D. Stula
-#  
+#
 #  Created by Gregory D. Stula on 1/4/16.
-#  
+#
 
-echo "Attempting to grab Microsoft fonts..."
-
-# Search for dependencies
 KERNAL=`uname`
 
-if [[ $KERNAL == "Linux" ]]; then
-    if [ ! -f /usr/bin/cabextract ] || [ -f /usr/bin/mkfontsdir ]; then
-        echo "Dependencies missing! Please run \`\$PACKAGE_MANAGER install cabextract curl\` and try again."
-        exit
-    fi
+
+# Search for dependencies
+if [[ $KERNAL == "Linux" ]] || [[ $KERNAL == "FreeBSD" ]]; then
+	if  ! hash cabextract 2>/dev/null  ||  ! hash mkfontdir 2>/dev/null; then
+		echo "Dependencies missing! Please make sure cabextract and mkfontdir are availabe on your system and try again." >&2
+		exit
+	fi
 fi
 
-
-if [[ $KERNAL == "Darwin" ]] || [[ $KERNAL == "FreeBSD" ]]; then
-    if [ ! -f /usr/local/bin/cabextract ] || [ -f /usr/local/bin/mkfontsdir ]; then
-        echo "Dependencies missing! Please run \`\$PACKAGE_MANAGER install cabextract mkfontsdir curl\` and try again."
-        exit
-    fi
+if [[ $KERNAL == "Darwin" ]]; then
+	if ! hash cabextract 2>/dev/null; then
+		echo "Dependencies missing! Please run \`brew install cabextract\` and try again." >&2
+		exit
+	fi
 fi
+
+# Store original location to cd back to later
+LOCATION=`pwd`
+
+# tmp dir needs to be cleaned up from here on out
+mkdir temp
+function clean_up() {
+	cd "$LOCATION"
+	rm -rf temp
+}
+
+cd temp
 
 # Download PowerPointViewer.exe and extract it's contents
-set -e
-set -x
-LOCATION=`pwd`
-mkdir temp
-cd temp
-curl -O http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe
+echo "Attempting to download PowerPointViewer.exe via curl..."
+MS_URL="http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe"
+
+
+if hash curl 2>/dev/null; then
+	curl -O "$MS_URL"
+elif hash wget 2>/dev/null; then
+	echo "Falling back to wget..."
+	wget "$MS_URL"
+else
+	echo "Neither wget or curl are available on this system."
+	echo "Aborting..."
+	cd "$LOCATION"
+	clean_up
+fi
+
 cabextract -L -F ppviewer.cab PowerPointViewer.exe
 cabextract ppviewer.cab
 
-# Make fonts directory for true type fonts
-if [ ! -d ~/.fonts ]; then
-    mkdir ~/.fonts
+# For Darwin platforms just open the files and install through GUI
+if [[ $KERNAL == "Darwin" ]]; then
+	open *.TTF
+	echo "Please install fonts using GUI"
+	echo "You will should manually delete the temp dir in $LOCATION."
+	exit
 fi
 
-mv *.TTF ~/.fonts/
-cd ~/.fonts
+# Make fonts directory for true type fonts
+if [[ ! -d ~/.local/share/fonts ]]; then
+	mkdir -p ~/.local/share/fonts
+fi
+
+# Move TrueTypeFonts to fonts dir
+mv *.TTF ~/.local/share/fonts
+cd ~/.local/share/fonts
+
+
+# Create fonts.scale file
 mkfontscale
+
+# Set fontdir to ~/.local/share/fonts
 mkfontdir
-xset fp+ ~/.fonts
-xset fp rehash
-cd "$LOCATION"
-rm -rf temp
-echo "Successfully installed Microsoft Fonts"
+
+clean_up
+echo "Successfully installed Microsoft Fonts!"
